config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get "play", to: 'pages#play'
  get "countries/:id", to: 'countries#show', as: :country
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :wishes
  resources :visits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/continent.rb
class Continent < ApplicationRecord
  # has_many :countries
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :visits, dependent: :destroy
  has_many :wishes, dependent: :destroy
  belongs_to :world

  validates :name, :flag, :population, :capital, presence: true
  validates :population, numericality: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :country
  belongs_to :user

  validates :date, :notes, presence: true
  validates :notes, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :visits
  has_many :wishes
end

app/models/visit.rb
class Visit < Trip
  has_one_attached :photo, dependent: :destroy

  scope :latest, -> { order(date: :asc) }

  # callback methods
  after_create :increment_trip_count
  after_destroy :decrease_trip_count

  private

  def increment_trip_count
    user.trip_count += 1
    user.save!
  end

  def decrease_trip_count
    user.trip_count -= 1
    user.save!
  end
end

app/models/wish.rb
class Wish < Trip
end

app/models/world.rb
require_relative "country"

class World < ApplicationRecord
  has_many :countries
  has_many :wishes, through: :countries
  has_many :visits, through: :countries

  def self.population
    Country.pluck(:population).sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def show
    @country = Country.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :play ]

  def play
    count = Country.count
    random_offset = rand(count)
    @country = Country.offset(random_offset).first
    # @country = Country.all.sample
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :find_visit, only: [:edit, :update, :destroy]

  def index
    @visits = current_user.visits.latest
  end

  def new
    @visit = Visit.new
  end

  def create
    @visit = Visit.new(visit_params)
    @visit.user = current_user
    if @visit.save
      flash.notice = "One more trip added!"
      redirect_to visits_path
    else
      flash.alert = "Uh oh - didn't work"
      render :new
    end
  end

  def edit
  end

  def update
    if @visit.update(visit_params)
      redirect_to visits_path
    else
      flash.alert = "Uh oh - didn't work"
      render :edit
    end
  end

  def destroy
    @visit.destroy
    redirect_to visits_path
  end

  private

  def visit_params
    params.require(:visit).permit(:country_id, :date, :notes, :photo)
  end

  def find_visit
    @visit = Visit.find(params[:id])
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :find_wish, only: [:edit, :update, :destroy]

  def index
    @wishes = current_user.wishes.all
  end

  def new
    @wish = Wish.new
  end

  def create
    @wish = Wish.new(wish_params)
    @wish.user = current_user
    if @wish.save
      redirect_to wishes_path
      flash.notice = "You'll make it there soon!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wish.update(wish_params)
      redirect_to wishes_path
    else
      render :edit
    end
  end

  def destroy
    @wish.destroy
    redirect_to wishes_path
  end

  private

  def wish_params
    params.require(:wish).permit(:country_id, :date, :notes)
  end

  def find_wish
    @wish = Wish.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/show.html.erb
<div class="actions mt-5">
  <%= link_to "Back to your Wishlist", wishes_path, class: "navigation" %>
</div>

<div class="play-window mt-5">
  <img src=<%= @country.flag %> alt="">

  <h1><%= @country.name %></h1>

  <h3> Capital: <%= @country.capital&.split&.join(' ') %> </h3>

  <h3> Population: <%= number_with_delimiter(@country.population) %> </h3>

  <h3> Languages spoken: <%= @country.languages.gsub!(/\W/, " ") %> </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geography</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-layout">
  <%= video_tag "earth.mov", autoplay: :autoplay, loop: :loop, class: "home-video" %>


  <h1 id="welcome">Welcome to Geography</h2>
  <%= link_to 'Test your knowledge', play_path, class: "home-links", id: "play" %>
  <%= link_to 'Check out your Wishlist', wishes_path, class: "home-links", id: "wishlist" %>
  <%= link_to 'Reminisce over past trips', visits_path, class: "home-links", id: "visits" %>

</div>

app/views/pages/play.html.erb
<div class="list-header">
  <h1>Guess the Country</h1>
</div>

<div class="actions">
  <%= link_to "Back to home", root_path, class: "navigation" %>
</div>

<div class="play-window">

  <img src=<%= @country.flag %> alt="" style="border: 1px solid black" class="mb-1" >

  <form class="country-guess">
    <input type="text" id="country-guess" placeholder="Which country has this flag?">
    <input type="submit">
  </form>
  <h1 class="d-none country-name"><%= @country.name %></h1>

  <form action="" class="capital-guess">
    <input type="text" id="capital-guess" placeholder="Country's capital?">
    <input type="submit">
  </form>
  <h3 class="d-none capital-name"> Capital: <%= @country.capital&.split&.join(' ') %> </h3>

  <form action="" class="population-guess">
    <input type="text" id="population-guess" placeholder="Country's population?">
    <input type="submit">
  </form>
  <h3 class="d-none population"> Population: <%= number_with_delimiter(@country.population) %> </h3>

  <%= link_to "Reload", play_path, class: "reload" %>
</div>

<%= javascript_pack_tag 'countries' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo_1.png", style: 'width:100px' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Play!", play_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wishlist", wishes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Past trips", visits_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/visits/edit.html.erb
<div class="list-header">
  <h1>Edit your trip to <%= @visit.country.name %> </h1>
</div>

<div class="form">
  <%= simple_form_for @visit do |f| %>
    <%= f.association :country, collection: Country.order('name ASC'), label_method: :name, value_method: :id, placeholder: @visit.country.name %>
    <%= f.input :date, as: :date, start_year: Date.today.year - 10, end_year: Date.today.year, order: [:month, :year], discard_day: true %>
    <%= f.input :notes %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn-primary" %>
  <% end %>
  <%= link_to 'Cancel', visits_path, style:"color: grey" %>
</div>

app/views/visits/index.html.erb
<div class="list-header">
  <h1>Your Past Trips</h1>
  <h3><%= pluralize(current_user.trip_count, 'trip') %> and counting...</h3>
</div>

<% if @visits.empty? %>
  <div class="list empty-list">
    <p>You haven't been anywhere yet!</p>
    <%= link_to 'Add a trip here', new_visit_path, class: "navigation new" %>
  </div>
<% else %>
  <table class='list'>
    <tr>
      <th></th>
      <th></th>
      <th class='column-one'>Country</th>
      <th>Date</th>
      <th>Notes</th>
      <th></th>
    </tr>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to edit_visit_path(visit) do %>
            <i class="fas fa-edit" style="color:black"></i>
          <% end %>
        </td>
        <td><%= button_to visit_path(visit), method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
            <i class="fas fa-trash-alt" style="color:black; background:none; border:none"></i>
          <% end %>
        </td>
        <td class='column-one'>
          <%= visit.country.name %>
        </td>
        <td><%= visit.date.strftime('%B %Y') %></td>
        <td><%= visit.notes %></td>
        <td>
          <% if visit.photo.attached? %>
            <button type="button" class="fas fa-paperclip" data-bs-toggle="modal" data-bs-target="#countryImage"></button>
            <div class="modal fade" id="countryImage" tabindex="-1" aria-labelledby="countryImageLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="countryImageLabel"><%= visit.country.name %></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= cl_image_tag visit.photo.key, height: 300, width: 465, crop: :fill %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="4">
        <%= link_to "Add somewhere else you've visited", new_visit_path %>
      </td>
    </tr>
  </table>
<% end %>


<%= javascript_pack_tag 'visits' %>

app/views/visits/new.html.erb
<div class='list-header'>
  <h1>Add a trip</h1>
</div>

<div class='form'>
  <%= simple_form_for @visit do |f| %>
    <%= f.association :country, collection: Country.order('name ASC'), label_method: :name, value_method: :id, prompt: "-- SELECT ONE --" %>
    <%= f.input :date, as: :date, start_year: Date.today.year - 10, end_year: Date.today.year, order: [:month, :year], discard_day: true %>
    <%= f.input :notes, placeholder: "max 30 characters", input_html: { maxlength: 30 } %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "navigation new" %>
  <% end %>
  <%= link_to 'Cancel', visits_path, style:"color: grey" %>
</div>

app/views/wishes/_form.html.erb
<div class='form'>
  <%= simple_form_for wish do |f| %>
    <%= f.input :date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 15, order: [:month, :year], discard_day: true %>
    <%= f.input :notes, placeholder: "max 30 characters", input_html: { maxlength: 30 } %>
    <%= f.submit %>
    <%= link_to 'Cancel', wishes_path, style: 'color: grey' %>
  <% end %>
</div>

app/views/wishes/edit.html.erb
<div class='list-header'>
  <h1>Edit your future trip to <%= @wish.country.name %></h1>
</div>

<%= render partial: "form", locals: { wish: @wish } %>

app/views/wishes/index.html.erb
<div class='list-header'>
  <h1>Your Wishlist</h1>
</div>

<% if @wishes.empty? %>
  <div class="list empty-list">
    <p>You don't have anything on your Wishlist yet!</p>
    <%= link_to 'Create your first', new_wish_path, class: "navigation new" %>
  </div>
<% else %>
  <table class="list">
    <tr>
      <th></th>
      <th></th>
      <th class='column-one'>Country</th>
      <th>Budget</th>
      <th>Who's going with you?</th>
    </tr>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= link_to edit_wish_path(wish) do %>
            <i class="fas fa-edit" style="color:black"></i>
          <% end %>
        </td>
        <td><%= button_to wish_path(wish), method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
            <i class="fas fa-trash-alt" style="color:black"></i>
          <% end %>
        </td>
        <td class='column-one'>
          <%= link_to wish.country.name, country_path(wish.country) %>
        </td>
        <td><%= wish.date.strftime('%B %Y') %></td>
        <td><%= wish.notes %></td>
      </tr>
      <%# be able to click on a wish to say you've been and make it a "visit" %>
      <%# add the date and notes %>
      <%# redirect to visits index %>
    <% end %>
    <tr>
      <td colspan="4">
        <%= link_to "Why not add another?", new_wish_path %>
      </td>
    </tr>
  </table>
<% end %>

app/views/wishes/new.html.erb
<div class='list-header'>
  <h1>Add to your Wishlist</h1>
</div>

<div class='form'>
  <%= simple_form_for @wish do |f| %>
    <%= f.association :country, collection: Country.order('name ASC'), label_method: :name, value_method: :id, prompt: "-- SELECT ONE --" %>
    <%= f.input :date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 15, order: [:month, :year], discard_day: true %>
    <%= f.input :notes, placeholder: "max 30 characters", input_html: { maxlength: 30 } %>
    <%= f.button :submit, class: "navigation new", style: "" %>
  <% end %>
  <%= link_to 'Cancel', wishes_path, style: 'color: grey' %>
</div>